# Generated by Django 2.1.7 on 2019-06-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_category', models.CharField(choices=[('G', 'GENERAL ADMISSION'), ('E', 'EARLY BIRD'), ('C', 'CHILDREN'), ('S', 'SENIOR')], max_length=1)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event.Event')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='event.Ticket'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
