# Generated by Django 2.1.7 on 2019-06-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190622_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
