# Generated by Django 2.1.7 on 2019-06-25 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190622_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_category',
            new_name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tickets',
        ),
        migrations.AddField(
            model_name='orderedticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='event.Ticket'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tickets',
            field=models.ManyToManyField(related_name='cart', to='event.OrderedTicket'),
        ),
    ]
