# Generated by Django 2.1.7 on 2019-07-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190630_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('General admission', 'GENERAL ADMISSION'), ('Early bird', 'EARLY BIRD'), ('Children', 'CHILDREN'), ('Senior', 'SENIOR')], max_length=20),
        ),
    ]
