# Generated by Django 2.1.7 on 2019-07-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=1),
        ),
    ]
